### ISSUE TITLE
How to Use XR-Transformer in Text2Text App

### ISSUE THREAD

**Issue by lyy1994** [amzn/pecos#140]
## Description
I want to use XR-Transformer in text2text app, following the parameters given [here](https://github.com/amzn/pecos/blob/mainline/examples/xr-transformer-neurips21/params/wiki10-31k/bert/params.json). But setting `--params-path` to this .json file raise the error:
```
Traceback (most recent call last):
  File "/home/huziyuan/miniconda3/envs/huggingface/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/huziyuan/miniconda3/envs/huggingface/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/huziyuan/miniconda3/envs/huggingface/lib/python3.9/site-packages/pecos/apps/text2text/train.py", line 345, in <module>
    train(args)
  File "/home/huziyuan/miniconda3/envs/huggingface/lib/python3.9/site-packages/pecos/apps/text2text/train.py", line 328, in train
    t2t_model = Text2Text.train(
  File "/home/huziyuan/miniconda3/envs/huggingface/lib/python3.9/site-packages/pecos/apps/text2text/model.py", line 317, in train
    pred_params = pred_params.override_with_kwargs(kwargs)
  File "/home/huziyuan/miniconda3/envs/huggingface/lib/python3.9/site-packages/pecos/apps/text2text/model.py", line 126, in override_with_kwargs
    self.xlinear_params.override_with_kwargs(pred_kwargs)
AttributeError: 'NoneType' object has no attribute 'override_with_kwargs'
```

## References
- [Text2Text API](https://github.com/amzn/pecos/blob/mainline/pecos/apps/text2text/README.md)
- [XR-Transformer](https://github.com/amzn/pecos/tree/mainline/examples/xr-transformer-neurips21)

**Comment by lyy1994** [comment]
Another question: if I want to apply PECOS to the XMC problem with Chinese text corpus, what kind of adjustment should I do? Does it support Chinese, e.g., the tf-idf feature extraction?

**Comment by jiong-zhang** [comment]
Hi @lyy1994 , currently text2text only support XR-Linear model. The PECOS TFIDF vectorizer support word level, character level tokenization. For Chinese, you may want to use character level tokenization or insert spaces between Chinese characters and use word level tokenization.

**Comment by lyy1994** [comment]
Thanks for your reply! If I follow [XR-Transformer](https://github.com/amzn/pecos/tree/mainline/examples/xr-transformer-neurips21) to perform XMC and I have both the text and the extracted visual features (in .npy format), how am I supposed to fuse these multimodal features in XR-Transformer?

**Comment by jiong-zhang** [comment]
XR-Transformer supports both additional dense and sparse features. You can just replace the sparse TF-IDF features [here](https://github.com/amzn/pecos/blob/mainline/examples/xr-transformer-neurips21/train_and_predict.sh#L11) with your dense instance feature. Or you could follow the example [here](https://github.com/amzn/pecos/tree/mainline/pecos/xmc/xtransformer#python-example) (i.e. replace `train_feat.npz` with your `train_feat.npy`) in python API.
