### ISSUE TITLE
Can't reproduce XR-Transformer Neurips results

### ISSUE THREAD

**Issue by celsofranssa** [amzn/pecos#207]
Trying to reproduce XR-Transformer results gives me the following error during [training and predicting](https://github.com/amzn/pecos/tree/mainline/examples/xr-transformer-neurips21#training-and-evaluation):
```python
02/17/2023 08:39:04 - INFO - __main__ - Setting random seed 0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xtransformer/train.py", line 582, in <module>
    do_train(args)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xtransformer/train.py", line 495, in do_train
    X_trn = smat_util.load_matrix(args.trn_feat_path, dtype=np.float32)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/utils/smat_util.py", line 117, in load_matrix
    mat = np.load(src)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './xmc-base/wiki10-31k//tfidf-attnxml/X.trn.npz'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xtransformer/predict.py", line 176, in <module>
    do_predict(args)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xtransformer/predict.py", line 145, in do_predict
    xtf = XTransformer.load(args.model_folder)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xtransformer/model.py", line 195, in load
    text_encoder = TransformerMatcher.load(os.path.join(load_dir, "text_encoder"))
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xtransformer/matcher.py", line 359, in load
    raise ValueError(f"text_encoder does not exist at {encoder_dir}")
ValueError: text_encoder does not exist at models/wiki10-31k/bert/text_encoder/text_encoder
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xlinear/evaluate.py", line 72, in <module>
    do_evaluation(args)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/xmc/xlinear/evaluate.py", line 62, in do_evaluation
    Y_true = smat_util.load_matrix(args.truth_path).tocsr()
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/utils/smat_util.py", line 117, in load_matrix
    mat = np.load(src)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './xmc-base/wiki10-31k//Y.tst.npz'
Traceback (most recent call last):
  File "ensemble_evaluate.py", line 58, in <module>
    do_evaluation(args)
  File "ensemble_evaluate.py", line 49, in do_evaluation
    Y_true = sorted_csr(load_matrix(args.truth_path).tocsr())
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/pecos/utils/smat_util.py", line 117, in load_matrix
    mat = np.load(src)
  File "/home/celso/projects/venvs/pecos/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './xmc-base/wiki10-31k//Y.tst.npz'

```

**Comment by jiong-zhang** [comment]
The error indicates you don't have the dataset ready. Please follow the instructions in the README to download the dataset first.

**Comment by celsofranssa** [comment]
Sorry, I had already downloaded the dataset, but it was stored on a different server for some reason.
