### ISSUE TITLE
Text2Text Errors out if label-embed-type is not 'pifa'

### ISSUE THREAD

**Issue by simonhughes22** [amzn/pecos#33]
## Description
I am trying to train a text2text model using label embeddings other than just the PIFA embeddings. Ideally i'd like to use tf-idf features computed over the labels, as one of the described options in the paper. When i tried using 

```
--label-embed-type pifa_lf_concat
```

I get the following error, as the code is not passing the Label Feature matrix Z to the label embedding logic

```
Traceback (most recent call last):
  File "/opt/conda/envs/pecos/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/pecos/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/pecos/lib/python3.8/site-packages/pecos/apps/text2text/train.py", line 308, in <module>
    train(args)
  File "/opt/conda/envs/pecos/lib/python3.8/site-packages/pecos/apps/text2text/train.py", line 277, in train
    t2t_model = Text2Text.train(
  File "/opt/conda/envs/pecos/lib/python3.8/site-packages/pecos/apps/text2text/model.py", line 315, in train
    label_feat_set[embed_type] = LabelEmbeddingFactory.create(Y, X, method=embed_type)
  File "/opt/conda/envs/pecos/lib/python3.8/site-packages/pecos/xmc/base.py", line 1540, in create
    return mapping[method.lower()](Y, X, **kwargs)
```

## How to Reproduce?
Train a text2text model with ```--label-embed-type pifa_lf_concat ```

## Environment
- Operating system: Unix Ubuntu (on GCP)
- Python version:     3.8
- PECOS version:     0.1.0

**Comment by simonhughes22** [comment]
I'd also just like an option to use tf idf embeddings from the labels (on their own). I don't see an option for that in the text2text library (despite the name). I can write this myself using the regular library but it would be awesome if you can add that as an option here, as you clearly experimented with that in the paper.

**Comment by OctoberChang** [comment]
@simonhughes22 , we just added the functionality to support --label-embed-type pifa_lf_concat in the text2text command line interface. Feel free to check it out and let us know if you encouter any issue.

An example usage would be:
``` bash
python -m pecos.apps.text2text.train \
  --label-embed-type pifa_lf_concat::Z=${Z_pifa_file} \
  -i ${train_file} \ 
  -m ${model_folder}

```
